services:
    - type: web
      name: tcu-website-sample
      env: docker
      plan: free
      dockerfilePath: ./Dockerfile
      # Render automatically sets $PORT for the web service
      buildCommand: |
          npm install
          npm run build
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
      startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: 'false'
          - key: APP_KEY
            value: base64:GENERATE_YOUR_KEY
          - key: APP_URL
            value: https://tcu-website-sample.onrender.com
