services:
    - type: web
      name: tcu-website-sample
      env: docker
      plan: free
      dockerfilePath: ./Dockerfile
      buildCommand: |
          npm install
          npm run build
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
      startCommand: apache2-foreground
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: 'false'
