services:
    - type: web
      name: tcu-website-sample
      env: php
      plan: free
      buildCommand: |
          composer install
          php artisan key:generate
          npm install
          npm run build
      startCommand: php artisan serve --host 0.0.0.0 --port 10000
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: false
          - key: APP_URL
            value: https://tcu-website-sample.onrender.com
          - key: DB_CONNECTION
            value: sqlite
          - key: DB_DATABASE
            value: /tmp/database.sqlite
